# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'RSVP',  url: 'rsvp'}
- {name: 'Registry and Gifts', url: 'registry'}
- {name: 'Wedding Venue',      url: 'weddingvenue'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Next section'
  previous_page: 'Previous section'

sharing_button_prompt: ''

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
